name: intray-api
version: '0.0.0.0'
synopsis: Intray API
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - JuicyPixels
  - JuicyPixels-extra
  - aeson
  - autodocodec
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - bytestring >=0.10 && <0.11
  - containers
  - cookie
  - hashable
  - intray-cli-data
  - intray-data
  - mergeless
  - monad-logger
  - servant
  - servant-auth
  - servant-auth-server
  - servant-blaze
  - text
  - time
  - typed-uuid
  - uuid >=1.3 && <1.4
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers
  - validity-text >=0.2
  - validity-time >=0.1
  - validity-uuid >=0.0
  - wai

