name: intray-data-gen
version: '0.0.0.0'
synopsis: Generators for intray-data

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - bytestring
  - genvalidity >=1.0
  - genvalidity-bytestring
  - genvalidity-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-typed-uuid
  - genvalidity-uuid
  - intray-data
  - text
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  intray-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - QuickCheck
    - bytestring
    - intray-data
    - intray-data-gen
    - sydtest
    - sydtest-persistent-sqlite
    - text
